import json
import hashlib
from datetime import date
from pathlib import Path
from typing import Iterator

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from app.core.config import Settings
from app.models import EmergencyPattern, ReviewStatus, SafetyLevel, SessionStatus
from app.triage.engine import TriageLevel
from app.llm.provider import LLMUnavailableError
from app.persistence.database import build_engine
from app.persistence.repositories import MessageRepository, SessionRepository, TraceRepository

from conversation_support import (
    OrchestratorHarness,
    case_json,
    incomplete_case_json,
    questions_json,
    make_pattern,
    make_signal_rule,
)
from test_conversation_api import (
    app_and_client,
    create_session,
    send_message,
    inject_orchestrator,
)

# --- B. EMERGENCY PRE-SCREEN BYPASS INVARIANT ---
def test_invariant_emergency_bypass_skips_llm(tmp_path: Path) -> None:
    pattern = make_pattern("T-INV-PRE-1", "synthetic bypass trigger")
    # Must be APPROVED to activate
    pattern.review_status = ReviewStatus.APPROVED
    harness = OrchestratorHarness(tmp_path, patterns=[pattern]) # Provider queue is empty, would raise LLMUnavailable if called
    
    import asyncio
    session = harness.orchestrator.create_session()
    response = asyncio.run(
        harness.orchestrator.handle_message(session.id, "I have a synthetic bypass trigger right now")
    )
    
    assert response.triage.level is TriageLevel.EMERGENCY
    assert "T-INV-PRE-1" in response.triage.fired_rule_ids
    assert len(harness.provider.requests) == 0 # LLM NOT called
    assert harness.orchestrator.get_session(session.id).status is SessionStatus.ESCALATED

# --- C. LLM CANNOT OVERRIDE TRIAGE ---
def test_invariant_llm_cannot_override_triage(tmp_path: Path) -> None:
    # LLM outputs a case, we evaluate deterministic rules.
    # We will make sure the text generated by LLM during composition doesn't change triage.
    # Wait, the LLM generates a composition string. It doesn't generate triage.
    # The extraction generates a StructuredCase. Triage is purely deterministic based on StructuredCase.
    # Let's extract a case that maps to routine, but LLM adds confidence=1.0 or something. 
    # Actually, composition outputs just text.
    harness = OrchestratorHarness(tmp_path, scripts=(case_json(), "You must go to the emergency room immediately!"))
    import asyncio
    session = harness.orchestrator.create_session()
    response = asyncio.run(harness.orchestrator.handle_message(session.id, "routine synthetic issue"))
    
    assert response.triage.level is TriageLevel.SELF_CARE
    # The output text might say emergency but triage level is deterministic
    assert response.triage.level != TriageLevel.EMERGENCY

# --- D. OUTPUT POLICY CANNOT OVERRIDE TRIAGE ---
def test_invariant_output_policy_cannot_override_triage(tmp_path: Path) -> None:
    # If the LLM generates something violating policy, it falls back to a safe phrase.
    # This shouldn't change the TriageDecision object.
    harness = OrchestratorHarness(tmp_path, scripts=(case_json(), "You have a synthetic disease."))
    import asyncio
    session = harness.orchestrator.create_session()
    response = asyncio.run(harness.orchestrator.handle_message(session.id, "synthetic issue"))
    
    assert response.triage.level is TriageLevel.SELF_CARE
    assert "you have" not in response.user_message.en.lower() # Fallback used
    # Triage remained exactly what the engine decided

# --- E. UNKNOWN RED-FLAG SIGNAL FAIL-CLOSED ---
from unittest.mock import patch
def test_invariant_unknown_signal_fail_closed(tmp_path: Path) -> None:
    with patch('app.safety.signals._ALLOWED_SIGNALS', {'KNOWN_SYNTHETIC_SIGNAL'}):
        # Case reports an unknown and a known signal
        case_dict = json.loads(case_json())
        case_dict["red_flag_signals"] = ["KNOWN_SYNTHETIC_SIGNAL", "UNKNOWN_ROGUE_SIGNAL"]
        
        rule = make_signal_rule("T-R-KNOWN", "KNOWN_SYNTHETIC_SIGNAL", SafetyLevel.URGENT)
        # Attempt to make a rule for the unknown (shouldn't matter as extraction is filtered)
        rule_unknown = make_signal_rule("T-R-UNK", "UNKNOWN_ROGUE_SIGNAL", SafetyLevel.EMERGENCY)
        
        harness = OrchestratorHarness(tmp_path, scripts=(json.dumps(case_dict), "safe output"), rules=[rule, rule_unknown])
        import asyncio
        session = harness.orchestrator.create_session()
        response = asyncio.run(harness.orchestrator.handle_message(session.id, "synthetic message"))
        
        # Only the known signal triggers
        assert response.triage.level is TriageLevel.URGENT_SAME_DAY
        assert "T-R-KNOWN" in response.triage.fired_rule_ids
        assert "T-R-UNK" not in response.triage.fired_rule_ids

# --- F. UNAPPROVED EMERGENCY PATTERN INTEGRATION ---
def test_invariant_unapproved_pattern_cannot_trigger(tmp_path: Path) -> None:
    pat_draft = make_pattern("P-D", "draft word")
    pat_draft.review_status = ReviewStatus.DRAFT
    
    pat_pend = make_pattern("P-P", "pending word")
    pat_pend.review_status = ReviewStatus.PENDING_DOMAIN_REVIEW
    
    pat_rej = make_pattern("P-R", "rejected word")
    pat_rej.review_status = ReviewStatus.REJECTED
    
    pat_app = make_pattern("P-A", "approved word")
    pat_app.review_status = ReviewStatus.APPROVED
    
    import yaml
    from app.safety.loader import load_patterns_dir
    data = {
        "patterns": [
            pat_draft.model_dump(mode="json"),
            pat_pend.model_dump(mode="json"),
            pat_rej.model_dump(mode="json"),
            pat_app.model_dump(mode="json"),
        ]
    }
    test_file = tmp_path / "synthetic.yaml"
    test_file.write_text(yaml.dump(data), encoding="utf-8")
    loaded = load_patterns_dir(tmp_path)
    assert len(loaded) == 1
    assert loaded[0].id == "P-A"

# --- G. LLM FAILURE SAFETY INVARIANT ---
def test_invariant_llm_failure_safety(app_and_client) -> None:
    app, client, settings = app_and_client
    # Empty scripts -> LLMUnavailableError
    inject_orchestrator(app, settings)
    
    session_id = create_session(client)
    response = send_message(client, session_id, "synthetic health text")
    
    assert response.status_code == 503
    assert response.json()["error"]["code"] == "llm_unavailable"
    assert "Traceback" not in response.text
    assert "synthetic health text" not in response.text

# --- H. MALFORMED LLM OUTPUT ---
def test_invariant_malformed_llm_output_retries_and_safely_handles(tmp_path: Path) -> None:
    # Two malformed -> fallback to rephrase guidance
    harness = OrchestratorHarness(tmp_path, scripts=("invalid json", "still invalid json"))
    import asyncio
    session = harness.orchestrator.create_session()
    response = asyncio.run(harness.orchestrator.handle_message(session.id, "synthetic text"))
    
    assert response.triage.level is TriageLevel.NEEDS_MORE_INFO
    assert len(harness.provider.requests) == 2
    assert harness.orchestrator.get_session(session.id).status is SessionStatus.COLLECTING

# --- I. MULTILINGUAL SAFETY INVARIANT ---
@pytest.mark.parametrize("lang_str", ["en", "ur", "sd"])
def test_invariant_multilingual_safety_same(app_and_client, lang_str: str) -> None:
    app, client, settings = app_and_client
    inject_orchestrator(app, settings, scripts=(case_json(), "safe output"))
    
    session = client.post("/sessions", json={"preferred_language": lang_str}).json()
    response = send_message(client, session["id"], "synthetic message")
    
    assert response.status_code == 200
    # Triage must be self_care (from case_json) regardless of language
    assert response.json()["triage"]["level"] == "self_care"

# --- J. CLINICIAN SUMMARY BOUNDARY ---
def test_invariant_clinician_summary_boundary(tmp_path: Path) -> None:
    import asyncio
    # 1. Normal final guidance -> has summary
    harness1 = OrchestratorHarness(tmp_path, scripts=(case_json(), "output"))
    sess1 = harness1.orchestrator.create_session()
    resp1 = asyncio.run(harness1.orchestrator.handle_message(sess1.id, "synthetic"))
    assert resp1.clinician_summary is not None
    assert len(harness1.provider.requests) == 2 # 1 extract, 1 compose
    
    # 2. Emergency bypass -> has summary (deterministically constructed)
    pat = make_pattern("P-1", "bypass")
    pat.review_status = ReviewStatus.APPROVED
    harness2 = OrchestratorHarness(tmp_path, patterns=[pat])
    sess2 = harness2.orchestrator.create_session()
    resp2 = asyncio.run(harness2.orchestrator.handle_message(sess2.id, "bypass"))
    assert resp2.clinician_summary is None
    assert len(harness2.provider.requests) == 0 # NO LLM for emergency bypass summary
    
    # 3. Follow-up only -> NO summary
    harness3 = OrchestratorHarness(tmp_path, scripts=(incomplete_case_json(), questions_json(1)))
    sess3 = harness3.orchestrator.create_session()
    resp3 = asyncio.run(harness3.orchestrator.handle_message(sess3.id, "synthetic"))
    assert resp3.clinician_summary is None

# --- K. TRACE PRIVACY INTEGRATION ---
def test_invariant_trace_privacy_excludes_sensitive(tmp_path: Path) -> None:
    raw_input = "extremely sensitive raw patient input text"
    harness = OrchestratorHarness(tmp_path, scripts=(case_json(), "output"))
    import asyncio
    sess = harness.orchestrator.create_session()
    asyncio.run(harness.orchestrator.handle_message(sess.id, raw_input))
    
    traces = TraceRepository(harness.session_factory).list_for_session(sess.id)
    # Check that raw_input is nowhere in any trace
    for trace in traces:
        dump = trace.model_dump_json()
        assert raw_input not in dump
        if trace.step == "extraction":
            # Input hash MUST be present and match
            assert trace.input_hash == hashlib.sha256(raw_input.encode("utf-8")).hexdigest()

# --- L. API ERROR SANITIZATION ---
def test_invariant_api_error_sanitization(app_and_client) -> None:
    app, client, settings = app_and_client
    
    # 1. empty message
    sess_id = create_session(client)
    resp_empty = send_message(client, sess_id, "   ")
    assert resp_empty.status_code == 422
    assert "Traceback" not in resp_empty.text
    
    # 2. invalid session
    resp_inv = send_message(client, "invalid-session-123", "synthetic")
    assert resp_inv.status_code == 404
    assert "Traceback" not in resp_inv.text
    
    # 3. malformed LLM -> well, we tested provider failure in G.
